### ISSUE TITLE
Installing on CentOS

### ISSUE THREAD

**Issue by AndrewsK30** [beschulz/wav2json#16]
How to intall on centOS?

error while loading shared libraries: libboost_program_options.so.1.42.0: cannot open shared object file: No such file or directory

**Comment by beschulz** [comment]
Hi Andrews,

you can have a look at the CentOS instructions for wav2png (
https://github.com/beschulz/wav2png#on-centos). building should be very
similar and
easy to adapt. If don't have a CentOS machine. If you have adapted the
instructions, a pull-request (or just paste it in the ticket) would be very
welcome.

Best,
Ben

**Comment by AndrewsK30** [comment]
i installed boost with following command:
`sudo yum install boost-devel.x86_64`

and then move wav2json from linux folder to usr/bin and give the error

**Comment by beschulz** [comment]
could you please remove the binary and re-compile?

**Comment by AndrewsK30** [comment]
Ok worked here is it:
    sudo yum install boost-devel
    sudo yum install libsndfile-devel
    cd ~/
    mkdir wave2json && cd wave2json/
    git clone https://github.com/beschulz/wav2json.git
    cd wav2json/build/
    make all
    cd ../bin/Linux/
    mv wav2json /usr/bin/

**Comment by beschulz** [comment]
Awesome, thanks. I'll update the documentation.

**Comment by beschulz** [comment]
I've updated the README.md with the build instructions for CentOS.
