### ISSUE TITLE
Normalizing json data

### ISSUE THREAD

**Issue by chinshr** [beschulz/wav2json#18]
Is there a way to normalize the JSON data, i.e. I want the loudest peaks to be 1/-1 and the rest amplified.

**Comment by beschulz** [comment]
Hi Juergen,

currently not from within wav2json. But you can of course normalize the
audio before feeding it into wav2json.

Best,
Ben

Juergen Fesslmeier <notifications@github.com> schrieb am Mi., 6. Apr. 2016,
07:12:

**Comment by chinshr** [comment]
Yes, i was thinking about that using min/max parameters and getting data from ffmpeg. Do you know how one would do that?

**Comment by beschulz** [comment]
the problem is, that --db-min / --db-max is only used when using decibel
(logarithmic) scaling for output. Maybe you can use sox?
https://www.learnosity.com/blog/2009/11/normalising-audio-with-sox/

Admittedly not the most efficient way to do it, but maybe worth a try.

**Comment by chinshr** [comment]
I will try using sox, thanks for the info!
