### ISSUE TITLE
GPL version

### ISSUE THREAD

**Issue by akreal** [beschulz/wav2json#19]
I tried to package wav2json for Gentoo and put GPL-1 as license in package metadata. People [doubt](https://github.com/gentoo/gentoo/pull/1809#discussion_r69272765) it should be version 1. What version of GPL do you really mean?

**Comment by beschulz** [comment]
Hi Pavel,

that's pretty cool. I updated the readme to reflect, that I really mean
GPL-2.

Best,
Ben

**Comment by akreal** [comment]
Great, thanks!
And thank you for this handy tool.
