### ISSUE TITLE
Why is min > max ?

### ISSUE THREAD

**Issue by evoyy** [beschulz/wav2json#20]
I am evaluating this tool for use in my project and I found some unexpected behaviour.

I used the following command to extract data from a small wav file:

    wav2json --channels min max --samples 10 testfile.wav

which produces the following output:

    {
      "_generator":"wav2json version 0.4 on Linux (http://goo.gl/af7wg)",
      "min": [0.205109,0.788055,0.34726,0.293579,0.346283,0.402222,0.301666,0.378906,0.461487,0.848633],
      "max": [0.297516,0.938629,0.344421,0.375366,0.482239,0.434235,0.291504,0.527985,0.502594,0.854004],
      "duration":7.999615
    }

For some of the data, the min value is greater than the max value. I am not very familiar with C++, but I looked at the code and it seems that min/max are calculated from the same block of samples. I don't understand how min can be greater than max. Please can you help me to understand what is happening?

**Comment by beschulz** [comment]
Hi,

actually I'm not sure how useful min and max are. Do you have a use-case in
mind?

But anyways, here's what happens:
imagine you have an audio file of 1000 samples and want to export 100
datapoints from it. This
would mean, that 10 consecutive samples are aggregated for one datapoint to
export.
first, the min value of the left and right channel is taken, then 10
samples are aggregated via
max() (
https://github.com/beschulz/wav2json/blob/master/src/wav2json.cpp#L188).
Thus the
exported value is the max of the min in the range of samples.

So I'd consider this a bug. To fix that, one could either remove the min
option or use min()
for aggregation if channel = Options::MIN

so, #L188 becomes
if (channel == Options::MIN)
max = std::min( max, abs_sample );
else
max = std::max( max, abs_sample );

Obviously this needs testing and variable renaming.

Best,
Ben

**Comment by beschulz** [comment]
Ah - and one should also consider the std::abs() in L187. Otherwise what I was saying does not make much sense.

**Comment by evoyy** [comment]
Ok, thanks for the explanation.

This is my use case: I want to generate a single waveform that represents a stereo file.  To do this I need to plot data from more than one channel. I believe the way that software such as Audacity does this is by plotting data from both the max and min data. The max data is is plotted above the x axis, the min data below. This produces a waveform that is asymmetrical across the x axis.

This is how wavesurfer.js generates its waveforms, using data extracted with https://github.com/bbcrd/audiowaveform. However, I prefer the simplicity and design of wav2json, which allows to extract a fixed number of samples, whereas with audiowaveform the number of samples corresponds to the length of the audio (and also comes with dependencies and features I don't need such as zooming and exporting to png).

**Comment by beschulz** [comment]
Interesting idea!

If you're doing the plotting yourself, could't you use "left" for the upper
half and "right" for the lower half of the waveform you're drawing?

If you're not plotting the waveform yourself, can you provide me with a
sample of how the input data and output should look like?

Best,
Ben

**Comment by evoyy** [comment]
I thought about using left and right. But there are a couple of reasons not to. First, if the audio file is mono, this will produce a one-sided waveform. Second, suppose a track has some sounds only in the left channel such as during the intro. This would produce a waveform something like this, which looks a bit ugly:

![waveform1](https://cloud.githubusercontent.com/assets/1623890/16995875/dbce21d6-4eae-11e6-9c47-c3dbea330bd3.png)

**Comment by evoyy** [comment]
I have been experimenting, and I'm having trouble with your suggested change https://github.com/beschulz/wav2json/issues/20#issuecomment-233916559. The min array is all zeros. This is due to my inexperience with C++.

````
-        max = std::max( max, abs_sample );
+        if (channel == Options::MIN) {
+            max = std::min( max, abs_sample );
+        }
+        else {
+            max = std::max( max, abs_sample );
+        }
````

I don't understand this line https://github.com/beschulz/wav2json/blob/master/src/wav2json.cpp#L181

````c++
sample_type max(0);
````

And I don't know what to do about https://github.com/beschulz/wav2json/blob/master/src/wav2json.cpp#L187

````c++
sample_type abs_sample = std::abs(sample);
````

**Comment by beschulz** [comment]
You need to initialize the Aggregation Variable with (named Max) with a
large value, i.e.

sample_type max(std::numeric_limits<sample_type>::max());

Best
Ben

evoyy <notifications@github.com> schrieb am Mi., 20. Juli 2016, 21:11:

**Comment by evoyy** [comment]
Thanks for the pointer, I got it working.

After some time experimenting I realized that the concept of "min" is not very helpful, since in most audio files there will occasionally be samples with a very low value, which will force the aggregation very low, usually to zero, which makes it impractical for drawing a waveform.

I will try using the left / right channels instead.

**Comment by evoyy** [comment]
Just reporting back to say that using left/right channels to create stereo waveforms has been a success. Taking 2000 samples per channel means plotting 4000 data points on the canvas. With a bit of throttling this doesn't impede performance much and I'm getting nice asymmetic waveforms.

![waveform2](https://cloud.githubusercontent.com/assets/1623890/17014661/eaf30efc-4f25-11e6-9c99-bb2fdd859910.png)

**Comment by beschulz** [comment]
Hi,

that's cool. Maybe that's something to include in my other project (
https://github.com/beschulz/wav2png) ?

Best,
Ben
