### ISSUE TITLE
lost files?

### ISSUE THREAD

**Issue by ucasiggcas** [beschulz/wav2json#28]
#include <sndfile.hh>
#include <boost/program_options.hpp>
#include "./version.hpp"

Dear,
I could not find these headers,could U help me ?
Thx

**Comment by beschulz** [comment]
Sorry for the enormous delay.

You need to install the dependencies (libsndfile and libboost-program-options) and run ```make``` at least once in the build directory. The latter will generate the version.hpp.

You can also try to install the dependencies via:
```bash
cd build
make install_dependencies
```

This should work on macOO and Debian/Ubuntu/etc.
