### ISSUE TITLE
Printing output to stdout

### ISSUE THREAD

**Issue by srubin** [beschulz/wav2json#4]
It would be nice to have an alternative to print the resulting JSON to stdout rather than writing to a file. It's not a big deal, but it's also probably pretty trivial to change in the code.

**Comment by pafro** [comment]
@beschulz Sorry to ask in a closed issue - but was this ever implemented?  If so how would I access it?

I'll like to use this script to save the call to a variable in a shell script and then use that variable elsewhere.  If I have to load it in from the file then remove the file I can do that too, just thought this way would be neater and cleaner.

**Comment by srubin** [comment]
looks like it https://github.com/beschulz/wav2json/pull/8

**Comment by pafro** [comment]
Ah, makes sense.  Sorry about that, just couldn't figure it out.

Working example:
```
wav2json /myfile.wav --channels left right mid side min max -n -o -
```

Cheers!

**Comment by beschulz** [comment]
Yes,

I just looked it up in the source, because I could not remember:
https://github.com/beschulz/wav2json/blob/master/src/main.cpp#L29

Best,
Ben
